###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    php-fpm:
      build: phpdocker/php-fpm
      container_name: netasvg-php-fpm
      working_dir: /application
      volumes:
        - ./:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      # command: /bin/sh -c "composer install && composer dump-autoload -o && php bin/console -vvv server:run 0.0.0.0:8000"
      command: php bin/console -vvv server:run 0.0.0.0:8000
